### ISSUE TITLE
AssertionError occurred.

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [titipakorn/multi_camera_multi_person_tracking#2]
I run this model and got the following issue.

```
 $ python3 multi_camera_multi_person_tracking.py -i ~/images/4p-c1.avi ~/images/4p-c2.avi -m ~/multi_camera_multi_person_tracking/intel/person-detection-retail-0013/FP32/person-detection-retail-0013.xml --m_reid ~/multi_camera_multi_person_tracking/intel/person-reidentification-retail-0288/FP32/person-reidentification-retail-0288.xml --config config.py --output_video output.mp4 

INFO:root:Opening file /home/ishihara/images/4p-c1.avi
INFO:root:Opening file /home/ishihara/images/4p-c2.avi
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "multi_camera_multi_person_tracking.py", line 164, in <module>
    main()
  File "multi_camera_multi_person_tracking.py", line 147, in main
    capture = MulticamCapture(args.i)
  File "/home/********/multi_camera_multi_person_tracking/utils/video.py", line 42, in __init__
    assert cap.isOpened()
AssertionError
```

Please fix it or let me know how to escape it.

**Comment by titipakorn** [comment]
Are you sure there is "/home/ishihara/images/4p-c2.avi" this file in your storage?

**Comment by Ishihara-Masabumi** [comment]
No, I made a mistake.
Thank you.
